config/routes.rb
Rails.application.routes.draw do
  get 'waiting_room/index'
  get 'waiting_room/video'

  get 'video/index'
  get 'video/chat'

  get 'clinic/index'
  get 'clinic/address'
  get 'clinic/final'
  get 'clinic/cliniclist'

  get 'clinician/index'
  get 'clinician/profile'
  get 'clinician/license'
  get 'clinician/final'
  get 'clinician/address'
  get 'clinician/info'
  get 'clinician/clist'

  get 'doctor/index'
  get 'doctor/profile'
  get 'doctor/license'
  get 'doctor/final'
  get 'doctor/address'
  get 'doctor/dlist'

  get 'patient/index'
  get 'patient/personinfo'
  get 'patient/address'
  get 'patient/profile'
  get 'patient/final'
  get 'patient/plist'

  get 'home/index'
  root :to=> 'home#index'
  get 'home/personal'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clinic_controller.rb
class ClinicController < ApplicationController
  def index
  end
end

app/controllers/clinician_controller.rb
class ClinicianController < ApplicationController
	def index
	end
end

app/controllers/doctor_controller.rb
class DoctorController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/patient_controller.rb
class PatientController < ApplicationController
  def index
  end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
  def index
  end
end

app/controllers/waiting_room_controller.rb
class WaitingRoomController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinic_helper.rb
module ClinicHelper
end

app/helpers/clinician_helper.rb
module ClinicianHelper
end

app/helpers/doctor_helper.rb
module DoctorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patient_helper.rb
module PatientHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/helpers/waiting_room_helper.rb
module WaitingRoomHelper
end

app/views/clinic/address.html.erb
<% provide(:title, "Clinic address") %>
<%= render 'patient/patient_header' %>
<h1>Address</h1>
<form class="address">
  	<div class="form-row row">
	    <div class="form-group col-lg-6">
	      <label for="inputadd1">Address Line1</label>
	      <input type="text" class="form-control form-control-lg" id="inputadd1" placeholder="">
	    </div>
	    <div class="form-group col-lg-6">
	      <label for="inputprovince">Province</label>
	      <input type="text" class="form-control form-control-lg" id="inputprovince" placeholder="">
	    </div>
  	</div>
 	 <div class="form-row row">
	  <div class="form-group col-md-6">
	    <label for="inputadd2">Address Line2</label>
	    <input type="text" class="form-control" id="inputadd2" placeholder="">
	  </div>
	  <div class="form-group col-md-6">
	    <label for="inputcountry">Country</label>
	    <input type="text" class="form-control" id="inputcountry" placeholder="">
	  </div>
  	</div>
  	<div class="form-row row">
	    <div class="form-group col-md-6">
	      <label for="inputcity">City</label>
	      <input type="text" class="form-control" id="inputcity" placeholder="">
	    </div>
	    <div class="form-group col-md-6">
	      <label for="inputcode">Postal Code</label>
	      <input type="text" class="form-control" id="inputcode" placeholder="">
	    </div>
  	</div>
</form>
	<div class="row text-center">
	  <%= link_to 'Cancel', root_path, class:"btn btn-primary next-btn btn-lg" %>
	  <%= link_to 'Next', clinic_final_path, class: "btn btn-primary btn-lg next-btn"%>
	</div>
<%= render 'patient/patient_footer' %>

app/views/clinic/cliniclist.html.erb
<% provide(:title, "Clinic list") %>
<div class="container">
	<div class="col-sm-8 col-sm-offset-2 row" style="margin-top: 60px;">
		<div class="col-sm-6">
			<h2>Clinics</h2>
		</div>
		<div class="col-sm-3 float-right pull-right">
			<%= link_to 'Add Clinic', clinic_index_path, class: 'btn btn-primary btn-lg btn-block' %>
		</div>
	</div>
</div>
<%= render 'patient/patient_header' %>
<div class="table-responsive">
  <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Primary ULI</th>
          <th>Family Phyiscian</th>
          <th>Default Insurer</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>John Example</td>
          <td>doctor@example1</td>
          <td>1231</td>
          <td>Doctor1</td>
          <td>A1234</td>
          <td>Active</td>
        </tr>
        <tr>
          <td>John Example</td>
          <td>doctor@example1</td>
          <td>1231</td>
          <td>Doctor1</td>
          <td>A1234</td>
          <td>Active</td>
        </tr>
        <tr>
          <td>John Example</td>
          <td>doctor@example1</td>
          <td>1231</td>
          <td>Doctor1</td>
          <td>A1234</td>
          <td>Active</td>
        </tr>
        <tr>
          <td>John Example</td>
          <td>doctor@example1</td>
          <td>1231</td>
          <td>Doctor1</td>
          <td>A1234</td>
          <td>Active</td>
        </tr>
        <tr>
         <td>John Example</td>
          <td>doctor@example1</td>
          <td>1231</td>
          <td>Doctor1</td>
          <td>A1234</td>
          <td>Active</td>
        </tr>
        <tr>
          <td>John Example</td>
          <td>doctor@example1</td>
          <td>1231</td>
          <td>Doctor1</td>
          <td>A1234</td>
          <td>Active</td>
        </tr>
      </tbody>
    </table>
</div>
<%= render 'patient/patient_footer' %>
		  

app/views/clinic/index.html.erb
<% provide(:title, "Clinic") %>
<%= render 'patient/patient_header' %>
	<form class="f">
	  <h1>Personal info</h1>
	    <div class="form-row row">
	      <div class="form-group col-lg-6">
	        <label for="inputfirstname">First Name</label>
	        <input type="text" class="form-control form-control-lg" id="iinputfirstname" placeholder="">
	      </div>
	      <div class="form-group col-lg-6">
	        <label for="inputphonenumber">Phone Number</label>
	        <input type="text" class="form-control form-control-lg" id="inputphonenumber" placeholder="">
	      </div>
	    </div>
	   <div class="form-row row">
	    <div class="form-group col-md-6">
	      <label for="inputlastname">Last Name</label>
	      <input type="text" class="form-control" id="inputlastname" placeholder="">
	    </div>
	    <div class="form-group col-md-6">
	      <label for="inputcellnumber">Cell Number</label>
	      <input type="text" class="form-control" id="cellnumber" placeholder="">
	    </div>
	    </div>
	    <div class="form-row row">
	      <div class="form-group col-md-6">
	        <label for="gender">Gender</label>
	        <select id="gender" class="form-control">
	          <option selected>Male</option>
	          <option>Female</option>
	        </select>
	      </div>
	      <div class="form-group col-md-6">
	        <label for="inputState">Status</label>
	        <select id="inputState" class="form-control">
	          <option selected>Active</option>
	          <option>Disable</option>
	        </select>
	      </div>
	    </div>
	    <div class="form-row row">
	      <div class="form-group col-md-6">
	        <label for="inputbirthday">Birthday</label>
	        <input type="text" class="form-control" id="inputbirthday" placeholder="">
	      </div>
	    </div>
	</form>
	<div class="row text-center">
	    <%= link_to 'Cancel', root_path, class:"btn btn-primary next-btn btn-lg" %>
	    <%= link_to 'Next', clinic_address_path, class: "btn btn-primary btn-lg next-btn" %>
	  </div>
<%= render 'patient/patient_footer' %>

app/views/clinician/address.html.erb
<%= render 'patient/patient_header' %>
<h1>Address</h1>
<form class="address">
  	<div class="form-row row">
	    <div class="form-group col-lg-6">
	      <label for="inputadd1">Address Line1</label>
	      <input type="text" class="form-control form-control-lg" id="inputadd1" placeholder="">
	    </div>
	    <div class="form-group col-lg-6">
	      <label for="inputprovince">Province</label>
	      <input type="text" class="form-control form-control-lg" id="inputprovince" placeholder="">
	    </div>
  	</div>
 	 <div class="form-row row">
	  <div class="form-group col-md-6">
	    <label for="inputadd2">Address Line2</label>
	    <input type="text" class="form-control" id="inputadd2" placeholder="">
	  </div>
	  <div class="form-group col-md-6">
	    <label for="inputcountry">Country</label>
	    <input type="text" class="form-control" id="inputcountry" placeholder="">
	  </div>
  	</div>
  	<div class="form-row row">
	    <div class="form-group col-md-6">
	      <label for="inputcity">City</label>
	      <input type="text" class="form-control" id="inputcity" placeholder="">
	    </div>
	    <div class="form-group col-md-6">
	      <label for="inputcode">Postal Code</label>
	      <input type="text" class="form-control" id="inputcode" placeholder="">
	    </div>
  	</div>
</form>
	<div class="row text-center">
	  <button type="button" class="btn btn-primary btn-lg">cancel</button>
	  <%= link_to 'Next', clinician_profile_path, class: "btn btn-primary btn-lg next-btn"%>
	</div>
<%= render 'patient/patient_footer' %>

app/views/clinician/clist.html.erb
<div class="container">
	<div class="col-sm-8 col-sm-offset-2 row" style="margin-top: 60px;">
		<div class="col-sm-6">
			<h2>Clinicians</h2>
		</div>
		<div class="col-sm-3 float-right pull-right">
			<%= link_to 'Add Clinician', clinician_index_path, class: 'btn btn-primary btn-lg btn-block' %>
		</div>
	</div>
</div>
<%= render 'patient/patient_header' %>
<div class="table-responsive">
  <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Practice ID</th>
          <th>Provider Status</th>
          <th>Specialty Code</th>
          <th>Provider Type</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>John Example</td>
          <td>doctor@example1</td>
          <td>1231</td>
          <td>Full Register</td>
          <td>General Practice</td>
          <td>Physician</td>
        </tr>
        <tr>
          <td>John Example</td>
          <td>doctor@example1</td>
          <td>1231</td>
          <td>Full Register</td>
          <td>General Practice</td>
          <td>Physician</td>
        </tr>
        <tr>
          <td>John Example</td>
          <td>doctor@example1</td>
          <td>1231</td>
          <td>Full Register</td>
          <td>General Practice</td>
          <td>Physician</td>
        </tr>
        <tr>
          <td>John Example</td>
          <td>doctor@example1</td>
          <td>1231</td>
          <td>Full Register</td>
          <td>General Practice</td>
          <td>Physician</td>
        </tr>
        <tr>
          <td>John Example</td>
          <td>doctor@example1</td>
          <td>1231</td>
          <td>Full Register</td>
          <td>General Practice</td>
          <td>Physician</td>
        </tr>
        <tr>
          <td>John Example</td>
          <td>doctor@example1</td>
          <td>1231</td>
          <td>Full Register</td>
          <td>General Practice</td>
          <td>Physician</td>
        </tr>
      </tbody>
    </table>
</div>
<%= render 'patient/patient_footer' %>
		  

app/views/clinician/index.html.erb
<% provide(:title, "Clinician") %>
<%= render 'patient/patient_header' %>
	<form class="f">
	  <h1>Personal info</h1>
	    <div class="form-row row">
	      <div class="form-group col-lg-6">
	        <label for="inputfirstname">First Name</label>
	        <input type="text" class="form-control form-control-lg" id="iinputfirstname" placeholder="">
	      </div>
	      <div class="form-group col-lg-6">
	        <label for="inputphonenumber">Phone Number</label>
	        <input type="text" class="form-control form-control-lg" id="inputphonenumber" placeholder="">
	      </div>
	    </div>
	   <div class="form-row row">
	    <div class="form-group col-md-6">
	      <label for="inputlastname">Last Name</label>
	      <input type="text" class="form-control" id="inputlastname" placeholder="">
	    </div>
	    <div class="form-group col-md-6">
	      <label for="inputcellnumber">Cell Number</label>
	      <input type="text" class="form-control" id="cellnumber" placeholder="">
	    </div>
	    </div>
	    <div class="form-row row">
	      <div class="form-group col-md-6">
	        <label for="gender">Gender</label>
	        <select id="gender" class="form-control">
	          <option selected>Male</option>
	          <option>Female</option>
	        </select>
	      </div>
	      <div class="form-group col-md-6">
	        <label for="inputState">Status</label>
	        <select id="inputState" class="form-control">
	          <option selected>Active</option>
	          <option>Disable</option>
	        </select>
	      </div>
	    </div>
	    <div class="form-row row">
	      <div class="form-group col-md-6">
	        <label for="inputbirthday">Birthday</label>
	        <input type="text" class="form-control" id="inputbirthday" placeholder="">
	      </div>
	    </div>
	</form>
	<div class="row text-center">
	    <%= link_to 'Cancel', root_path, class:"btn btn-primary next-btn btn-lg" %>
	    <%= link_to 'Next', clinician_info_path, class: "btn btn-primary btn-lg next-btn" %>
	  </div>
<%= render 'patient/patient_footer' %>

app/views/clinician/info.html.erb
<% provide(:title, "Clinician info") %>
<%= render 'patient/patient_header' %>
<h1>Clinician Information</h1>
<div class="main_panel_part">
    <form class="person">
      <div class="form-row row">
        <label for="practice_id" class="col-sm-2 col-form-label col-form-label-sm col-sm-offset-2">Practice ID</label>
        <div class="col-sm-6">
          <input type="text" class="form-control form-control-sm block" id="practice_id" placeholder="">
        </div>
      </div>
    </form>
</div>
	<div class="row text-center">
	  <%= link_to 'Cancel', root_path, class:"btn btn-primary next-btn btn-lg" %>
	  <%= link_to 'Next', clinician_address_path, class: "btn btn-primary btn-lg next-btn" %>
	</div>
<%= render 'patient/patient_footer' %>

app/views/clinician/profile.html.erb
<% provide(:title, "Clinician profile") %>
<%= render 'patient/patient_header' %>
<h1>Profile</h1>
<div class="main_panel_part">
	<div class="text-center">
		<div class="profile_pic">
			<span class="glyphicon glyphicon-user"></span>
		</div>	
	</div>
</div>
	<div class="row text-center">
	  <%= link_to 'Cancel', root_path, class:"btn btn-primary next-btn btn-lg" %>
	  <%= link_to 'Next', clinician_final_path, class: "btn btn-primary btn-lg next-btn" %>
	</div>
<%= render 'patient/patient_footer' %>

app/views/doctor/_doctor_person_info.html.erb
<form class="f">
  <h1>Personal info</h1>
    <div class="form-row row">
      <div class="form-group col-lg-6">
        <label for="inputfirstname">First Name</label>
        <input type="text" class="form-control form-control-lg" id="iinputfirstname" placeholder="">
      </div>
      <div class="form-group col-lg-6">
        <label for="inputphonenumber">Phone Number</label>
        <input type="text" class="form-control form-control-lg" id="inputphonenumber" placeholder="">
      </div>
    </div>
   <div class="form-row row">
    <div class="form-group col-md-6">
      <label for="inputlastname">Last Name</label>
      <input type="text" class="form-control" id="inputlastname" placeholder="">
    </div>
    <div class="form-group col-md-6">
      <label for="inputcellnumber">Cell Number</label>
      <input type="text" class="form-control" id="cellnumber" placeholder="">
    </div>
    </div>
    <div class="form-row row">
      <div class="form-group col-md-6">
        <label for="gender">Gender</label>
        <select id="gender" class="form-control">
          <option selected>Male</option>
          <option>Female</option>
        </select>
      </div>
      <div class="form-group col-md-6">
        <label for="inputState">Status</label>
        <select id="inputState" class="form-control">
          <option selected>Active</option>
          <option>Disable</option>
        </select>
      </div>
    </div>
    <div class="form-row row">
      <div class="form-group col-md-6">
        <label for="inputbirthday">Birthday</label>
        <input type="text" class="form-control" id="inputbirthday" placeholder="">
      </div>
    </div>
</form>
<div class="row text-center">
    <%= link_to 'Cancel', root_path, class:"btn btn-primary next-btn btn-lg" %>
    <%= link_to 'Next', doctor_license_path, class: "btn btn-primary btn-lg next-btn" %>
  </div>

app/views/doctor/index.html.erb
<% provide(:title, "Doctor") %>
<%= render 'patient/patient_header' %>
<%= render 'doctor/doctor_person_info' %>
<%= render 'patient/patient_footer' %>

app/views/doctor/profile.html.erb
<%= render 'patient/patient_header' %>
<h1>Profile</h1>
<div class="main_panel_part">
	<div class="text-center">
		<div class="profile_pic">
			<span class="glyphicon glyphicon-user"></span>
		</div>	
	</div>
</div>
	<div class="row text-center">
	  <%= link_to 'Cancel', root_path, class:"btn btn-primary next-btn btn-lg" %>
	  <%= link_to 'Add Doctor', doctor_final_path, class: "btn btn-primary btn-lg next-btn" %>
	</div>
<%= render 'patient/patient_footer' %>

app/views/home/index.html.erb
<% provide(:title, "Home") %>
<div class="container">
	<section id="appointment_panel">
		<div class="row appointment">
			<div class="col-sm-3">
				<div class="panel panel-default">
				  <div class="panel-body">
				   <h2 class="text-center">Completed Appointment</h2>
				  </div>
				</div>
			</div>
			<div class="col-sm-3">
				<div class="panel panel-default">
				  <div class="panel-body">
					<h2 class="text-center">Missed Appointment</h2>
				  </div>
				</div>
			</div>
			<div class="col-sm-3">
				<div class="panel panel-default">
				  <div class="panel-body">
					<h2 class="text-center">Patients</h2>
				  </div>
				</div>
			</div>
			<div class="col-sm-3 appointment_command">
			<%= link_to 'Add Patient', patient_index_path, class: 'btn btn-primary btn-lg btn-block' %>
			<%= link_to 'Add Doctor', doctor_index_path, class: 'btn btn-primary btn-lg btn-block' %>
			<%= link_to 'Add Clinician', clinician_index_path, class: 'btn btn-primary btn-lg btn-block' %>
			<%= link_to 'Add Clinic', clinic_index_path, class: 'btn btn-primary btn-lg btn-block' %>
			</div>
		</div>
	</section>
	<section id="date_picker">
		<div class="row">
			<div class="text-center col-md-2 col-md-offset-5">
				<div class='input-group date' id='datetimepicker1'>
	                    <input type='text' class="form-control" />
	                    <span class="input-group-addon">
	                        <span class="glyphicon glyphicon-calendar"></span>
	                    </span>
	            </div>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-4">
				<h4 class="text-center">Doctor 1</h4>
				<div style="overflow:hidden;">
				    <div class="form-group">
				        <div class="row">
				            <div class="col-md-12 main_calendar">
				                <div id="datetimepicker12"></div>
				            </div>
				        </div>
				    </div>
				    <script type="text/javascript">
				        $(function () {
				            $('#datetimepicker12').datetimepicker({
				                inline: true,
				                sideBySide: false
				            });
				        });
				    </script>
				</div>
			</div>
			<div class="col-sm-4">
				<h4 class="text-center">Doctor 2</h4>
				<div style="overflow:hidden;">
				    <div class="form-group">
				        <div class="row">
				            <div class="col-md-12 main_calendar">
				                <div id="datetimepicker13"></div>
				            </div>
				        </div>
				    </div>
				    <script type="text/javascript">
				        $(function () {
				            $('#datetimepicker13').datetimepicker({
				                inline: true,
				                sideBySide: false
				            });
				        });
				    </script>
				</div>
			</div>
			<div class="col-sm-4">
				<h4 class="text-center">Doctor 3</h4>
				<div style="overflow:hidden;">
				    <div class="form-group">
				        <div class="row">
				            <div class="col-md-12 main_calendar">
				                <div id="datetimepicker14"></div>
				            </div>
				        </div>
				    </div>
				    <script type="text/javascript">
				        $(function () {
				            $('#datetimepicker14').datetimepicker({
				                inline: true,
				                sideBySide: false
				            });
				        });
				    </script>
				</div>
			</div>
		</div>
	</section>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to image_tag('logo.png'), root_path, class: 'navbar-brand ' %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle main_menu_home" data-toggle="dropdown">
        	<span class="glyphicon glyphicon-th"></span>
        </a>
        <div class="dropdown-menu clin_dropdown_menu">
          <table class="table table-bordered">
            <tbody>
              <tr>
                <td>
                  <%= link_to "<span class='glyphicon glyphicon-user text-center'></span><span class='user_name text-center drop_item_text'>Patients</span>".html_safe, patient_plist_path, class: 'text-center' %> 
                </td>
                <td>
                   <%= link_to "<span class='glyphicon glyphicon-home'></span><span class='user_name text-center drop_item_text'>Home</span>".html_safe, root_path, class: 'text-center' %> 
                </td>
              </tr>
              <tr>
                <td>
                  <a href="/doctor/dlist">
                    <%=image_tag 'doctor-icon.png', class: 'img-responsive doctor-icon'%><span class="text-center doctor_item drop_item_text">Doctors</span></div>
                  </a>
                </td>
                <td>
                  <a href="/clinic/cliniclist">
                  <%=image_tag 'doctor-icon.png', class: 'img-responsive doctor-icon'%><span class="text-center drop_item_text">Clinics</span>
                  </a>
                </td>
              </tr>
              <tr>
                <td>
                  <a href="/clinician/clist">
                  <%=image_tag 'doctor-icon.png', class: 'img-responsive doctor-icon'%><span class="text-center drop_item_text">Clincians</span>
                  </a>
                </td>
                <td class="last_menu_icon">
                    <span class="glyphicon glyphicon-list-alt text-center" data-toggle="modal" data-target="#exampleModalCenter"></span>
                    <span class="text-center drop_item_text" data-toggle="modal" data-target="#exampleModalCenter">Reports</span>
                  </a>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </li>
    </ul>
    <div class="search_bar">
          <div class="form-group">
              <div class="icon-addon addon-lg">
                  <input type="text" placeholder="Search" class="form-control" id="search">
                  <label for="search" class="glyphicon glyphicon-search" rel="tooltip" title="search"></label>
              </div>
  	      </div>
    </div>
    <ul class="nav navbar-nav navbar-right user_account_icon">
      <li class="user_info"><a href="#"><span class="glyphicon glyphicon-user"></span><span class="user_name">John</span></a></li>
      <li class="login"><%= link_to "<span class='user_login'>Login</span>".html_safe, waiting_room_index_path %></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h3 class="modal-title" id="exampleModalLongTitle">Reports</h3>
      </div>
      <div class="modal-body">
          <div class="form-row row">
          <div class="form-group col-sm-6 input_doctor_patient">
            <label for="inputdoctor" class="col-sm-2 col-form-label">Doctor</label>
            <div class="col-sm-9 pull-right">
              <input type="text" class="form-control" id="inputdoctor">
            </div>
        </div>
        <div class="form-group col-sm-6 input_doctor_patient">
            <label for="inputpatient" class="col-sm-2 col-form-label">Patient</label>
            <div class="col-sm-9 pull-right">
              <input type="text" class="form-control" id="inputpatient">
            </div>
        </div>
        </div>
        <!-- date -->
        <div class="form-inline form-group row form-calendar">
          <div class="col-sm-6">
              <div class="form-group form-inline ">
                  <label for="inputdate">Date</label>
                  <div class='input-group date col-sm-9 pull-right' id='datetimepicker8'>
                      <input type='text' id="inputdate" class="form-control" />
                      <span class="input-group-addon">
                          <span class="glyphicon glyphicon-calendar">
                          </span>
                      </span>
                  </div>
              </div>
          </div>
          <div class='col-sm-6'>
                  <div class="form-group form-inline">
                      <label for="inputtime">Time</label>
                      <div class='input-group date col-sm-9 pull-right modal_time_picker' id='datetimepicker3'>
                          <input type='text' id="inputtime" class="form-control" />
                          <span class="input-group-addon">
                              <span class="glyphicon glyphicon-time"></span>
                          </span>
                      </div>
                  </div>
          </div>
        </div>
        <div class="form-group row ">
          <label for="appointement_type" class="col-sm-4 col-form-label">Appointment Type</label>
          <div class="col-sm-8 pull-right">
            <select id="appointement_type" class="form-control">
                <option selected>Initial Consult</option>
                <option>Initial Consult2</option>
              </select>
          </div>
      </div>
      <div class="form-group row">
          <label for="appointement_type" class="col-sm-2 col-form-label">Note</label>
          <div class="col-sm-10">
            <textarea class="form-control" rows="3"></textarea>
          </div>
      </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker8').datetimepicker({
                    icons: {
                        time: "fa fa-clock-o",
                        date: "fa glyphicon-calendar",
                        up: "fa fa-arrow-up",
                        down: "fa fa-arrow-down"
                    }
                });
            });
            $(function () {
                    $('#datetimepicker3').datetimepicker({
                        format: 'LT'
                    });
                });
        </script>
        <!-- end date -->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
        <%= link_to 'Enter Waiting Room', video_index_path, class:'btn btn-primary pull-right'%>
      </div>
    </div>
  </div>
</div>

app/views/patient/_patient_footer.html.erb
			</div>
		</div>
	</div>
</div>

app/views/patient/profile.html.erb
<% provide(:title, "Patient profile") %>
<%= render 'patient/patient_header' %>
<h1>Profile</h1>
<div class="main_panel_part">
	<div class="text-center">
		<div class="profile_pic">
			<span class="glyphicon glyphicon-user"></span>
		</div>	
	</div>
</div>
	<div class="row text-center pagenation_button">
	  <%= link_to 'Cancel', root_path, class:"btn btn-primary next-btn btn-lg" %>
	  <%= link_to 'Next', patient_final_path, class: "btn btn-primary btn-lg next-btn" %>
	</div>
<%= render 'patient/patient_footer' %>